kind: pipeline
name: penalties
type: docker

steps:
  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: registry.hub.docker.com
      repo: registry.hub.docker.com/tyleragostino/penalty_posts
      tags: latest
      cache_from: "registry.hub.docker.com/tyleragostino/penalty_posts:latest"
  - name: deploy
    image: plugins/webhook
    settings:
      urls: http://192.168.1.125:9996/api/stacks/webhooks/1b812d0f-88f6-477e-ae01-aaa6b416f313

trigger:
  branch:
    - main
  event:
    - push
