kind: pipeline
name: penalties
type: docker

steps:
  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: registry.hub.docker.com
      repo: registry.hub.docker.com/tyleragostino/penalty_posts
      tags: latest
      cache_from: "registry.hub.docker.com/tyleragostino/penalty_posts:latest"
  - name: deploy
    image: plugins/webhook
    settings:
      urls: https://portainer.portersparadise.com/api/stacks/webhooks/c1be8523-a664-45d6-a74d-55493153a333

trigger:
  branch:
    - main
  event:
    - push
